apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: catalogue
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: "{{ .Values.deployment.imageName }}:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        readinessProbe:
          # httpGet:
          #   path: /health
          #   port: 8080
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: catalogue
        resources:
          requests:
            cpu: {{ .Values.deployment.cpuRequest }}
            memory: {{ .Values.deployment.memoryRequestRequest }}
          limits:
            cpu: {{ .Values.deployment.cpuLimit }}
            memory: {{ .Values.deployment.memoryLimit }}
